### ISSUE TITLE
AppNext SDK causes crashes on Android API 26

### ISSUE THREAD

**Issue by ParkerK** [appnext/native_ads_examples#1]
>Exception java.lang.IllegalStateException: Not allowed to start service Intent { cmp=<My App Package>/com.appnext.base.services.OperationService (has extras) }: app is in background uid UidRecord{e150727 u0a110 SVC idle procs:1 seq(0,0,0)}

This is causing crashes on users with Android API 26, as AppNext doesn't seem to have updated their SDK for the changes in O: https://developer.android.com/preview/behavior-changes.html#back-all

I should add that this happened using:     freeCompile `com.appnext.sdk.adapters:mopub-native-ads:2.0.2.459`, was this fixed in `2.0.6.462`? I don't have a test device using 26, so I can't test myself. I only know the crashes happen due to crash logs from users

**Comment by omriariav** [comment]
@ParkerK Hi there, we will look into this and will let you know. As Android O (API 26) is about to be released soon, we will make sure our SDK is compatible with the changes and updates. Thank you again for letting us know.

**Comment by ParkerK** [comment]
On a side note, any chance you guys plan to open source the SDK, or at least some components? Would be useful for debugging and sharing fixes :) Either way, thanks for the quick reply to this issue!

**Comment by omriariav** [comment]
It is unlikely that we'll make it open source in the near future, but we'll definitely take any input from our developers community into our full attention. I will make sure to reach back once we release an Android API 26 ready version (couple of weeks).

**Comment by omriariav** [comment]
Hi @ParkerK, we released version 2.1.1.463 last week. This version is compatible with Android 8 (API 26).
